org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
version_minecraft=26.1.2
version_neoforge=26.1.2.27-beta
# Updating MDG does not seem to trigger a full decompile, but still causes parts of the flow to rerun. So we do not want
# the version to change unexpectedly in the middle of working on something. Update this when updating the NF dependency,
# check https://projects.neoforged.net/neoforged/ModDevGradle for the latest version
version_mdg=2.0.141
version_ie=12.4.3
version_jei=29.5.0.26
version_cctweaked=1.110.2
version_dualcodecs=0.1.2
version_buildnumber=194
modid=immersiveengineering
org.gradle.configuration-cache=true
